### ISSUE TITLE
학부정보 데이터가 필요합니다

### ISSUE THREAD

**Issue by alsco1234** [james98k/ai_project_team_11#2]
데이터 전처리 파일을 만들면서
과목코드('GEK100008')이나 학부명('전산전자공학부')를
학부코드('0')으로 바꿔야 하는 문제가 생겼습니다.

이때 과목코드 앞자리 'GEK', 'GLS'등이 어떤 학부명인지 한번에 파악하기 힘들어 보류해놓은 상태입니다.
학부명 역시 같은 함수를 쓰기에 보류해뒀습니다.

```
GEK = 글로벌리더십학부
GLS = 전산전자공학부
```
이런식으로 한번에 학부정보가 나오는 데이터가 있다면 공유 부탁드립니다.

없다면 하나하나 수강편람 뒤져서 만들겠지만요...😥

**Comment by djm06294** [comment]
찾은 것 같아요 사진에 나오지 않은 있는 수업도 있는지는 모르겠지만 나와있는 과목코드는 실제와 동일해요!

![학부별약자](https://user-images.githubusercontent.com/79846054/172203709-2e3cd9e8-d8a8-42a1-9208-04fcde8ae546.JPG)

**Comment by alsco1234** [comment]
감사합니다! 덕분에 해결했습니다

**Comment by james98k** [comment]
혹시 데이터 가공 되셨으면 올려주실 수 있으실까요~?
